temfullcn/ViewComponents/TranDauViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using temfullcn.Models;

namespace ttem2.ViewComponents
{
    public class TranDauViewComponent : ViewComponent
    {
        QlgiaiBongDaContext db = new QlgiaiBongDaContext();
        public TranDauViewComponent()
        {

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {

          var matrandaus = db.Trandaus.Take(8).ToList();


            return View("TranDau", matrandaus);
        }

    }
}

temfullcn/Views/Shared/Footer.cshtml
<div class="footer">
    <div class="left_footer"> <img src="images/footer_logo.png" alt="" width="170" height="49" /> </div>
    <div class="center_footer">
        Template name. All Rights Reserved 2008<br />
        <a href="http://csscreme.com"><img src="images/csscreme.jpg" alt="csscreme" border="0" /></a><br />
        <img src="images/payment.gif" alt="" />
    </div>
    <div class="right_footer"> <a href="#">home</a> <a href="#">about</a> <a href="#">sitemap</a> <a href="#">rss</a> <a href="contact.html">contact us</a> </div>
</div>

temfullcn/Views/Shared/Header.cshtml
<div id="header">
    <div id="logo"> <a href="#"><img src="../Tem/images/logo.png" alt="" border="0" width="237" height="140" /></a> </div>
    <div class="oferte_content">
        <div class="top_divider"><img src="../Tem/images/header_divider.png" alt="" width="1" height="164" /></div>
        <div class="oferta">
            <div class="oferta_content">
                <img src="../Tem/images/laptop.png" width="94" height="92" alt="" border="0" class="oferta_img" />
                <div class="oferta_details">
                    <div class="oferta_title">Samsung GX 2004 LM</div>
                    <div class="oferta_text"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco </div>
                    <a href="details.html" class="details">details</a>
                </div>
            </div>
            <div class="oferta_pagination"> <span class="current">1</span> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">5</a> </div>
        </div>
        <div class="top_divider"><img src="../Tem/images/header_divider.png" alt="" width="1" height="164" /></div>
    </div>
    <!-- end of oferte_content-->
</div>

temfullcn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - temfullcn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/temfullcn.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">temfullcn</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - temfullcn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

temfullcn/Views/Shared/_LayoutKiemTra.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Electronix Store</title>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <link rel="stylesheet" type="text/css" href="../Tem/style.css" />
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="iecss.css" />
    <![endif]-->
    <script type="text/javascript" src="../Tem/js/boxOver.js"></script>

    <script src="../jjs/jquery-1.7.2.min.js"></script>
    <script src="../jjs/superfish.js"></script>
    <script src="../jjs/jquery.scrolltotop.js"></script>
    <style>
        /* Phân trang */
        .product__pagination {
            text-align: center;
            margin-top: 20px;
        }

            .product__pagination ul {
                display: inline-flex;
                padding: 0;
                margin: 0;
                list-style: none;
            }

            .product__pagination li {
                margin: 0 3px; /* giảm khoảng cách giữa các phân trang */
            }

            .product__pagination a,
            .product__pagination span {
                padding: 4px 8px; /* giảm padding */
                text-decoration: none;
                border: 1px solid #ddd;
                border-radius: 3px; /* làm bo tròn nhỏ hơn */
                color: #333;
                background-color: #f1f1f1;
                font-size: 12px; /* giảm kích thước font */
            }

                .product__pagination a:hover,
                .product__pagination .current {
                    background-color: #007bff;
                    color: #fff;
                }

            .product__pagination .current {
                font-weight: bold;
            }
    </style>
</head>
<body>
    <div id="main_container">
        <div class="top_bar">
            <div class="top_search">
                <div class="search_text"><a href="#">Advanced Search</a></div>
                <input type="text" class="search_input" name="search" />
                <input type="image" src="images/search.gif" class="search_bt" />
            </div>
            <div class="languages">
                <div class="lang_text">Languages:</div>
                <a href="#" class="lang"><img src="images/en.gif" alt="" border="0" /></a> <a href="#" class="lang"><img src="images/de.gif" alt="" border="0" /></a>
            </div>
        </div>
      <partial name="Header"/>
        <div id="main_content">
            <div id="menu_tab">
                <div class="left_menu_corner"></div>
                <ul class="menu">


                    @await Component.InvokeAsync("TranDau")




                </ul>
                <div class="right_menu_corner"></div>
            </div>
            <!-- end of menu tab -->
            <div class="crumb_navigation"> Navigation: <span class="current">Home</span> </div>
            <div class="left_content">
                <div class="title_box">Categories</div>
                <ul class="left_menu">
                    <li class="odd"><a href="#">Processors</a></li>
                    <li class="even"><a href="#">Motherboards</a></li>
                    <li class="odd"><a href="#">Desktops</a></li>
                    <li class="even"><a href="#">Laptops &amp; Notebooks</a></li>
                    <li class="odd"><a href="#">Processors</a></li>
                    <li class="even"><a href="#">Motherboards</a></li>
                    <li class="odd"><a href="#">Processors</a></li>
                    <li class="even"><a href="#">Motherboards</a></li>
                    <li class="odd"><a href="#">Desktops</a></li>
                    <li class="even"><a href="#">Laptops &amp; Notebooks</a></li>
                    <li class="odd"><a href="#">Processors</a></li>
                    <li class="even"><a href="#">Motherboards</a></li>
                </ul>
                <div class="title_box">Special Products</div>
                <div class="border_box">
                    <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                    <div class="product_img"><a href="details.html"><img src="images/laptop.png" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Newsletter</div>
                <div class="border_box">
                    <input type="text" name="newsletter" class="newsletter_input" value="your email" />
                    <a href="#" class="join">join</a>
                </div>
                <div class="banner_adds"> <a href="#"><img src="images/bann2.jpg" alt="" border="0" /></a> </div>
            </div>
            <!-- end of left content -->
            @RenderBody()

            <!-- end of center content -->
            <div class="right_content">
                <div class="shopping_cart">
                    <div class="cart_title">Shopping cart</div>
                    <div class="cart_details">
                        3 items <br />
                        <span class="border_cart"></span> Total: <span class="price">350$</span>
                    </div>
                    <div class="cart_icon"><a href="#" title="header=[Checkout] body=[&nbsp;] fade=[on]"><img src="images/shoppingcart.png" alt="" width="48" height="48" border="0" /></a></div>
                </div>
                <div class="title_box">What’s new</div>
                <div class="border_box">
                    <div class="product_title"><a href="details.html">Motorola 156 MX-VL</a></div>
                    <div class="product_img"><a href="details.html"><img src="images/p2.gif" alt="" border="0" /></a></div>
                    <div class="prod_price"><span class="reduce">350$</span> <span class="price">270$</span></div>
                </div>
                <div class="title_box">Manufacturers</div>
                <ul class="left_menu">
                    <li class="odd"><a href="#">Sony</a></li>
                    <li class="even"><a href="#">Samsung</a></li>
                    <li class="odd"><a href="#">Daewoo</a></li>
                    <li class="even"><a href="#">LG</a></li>
                    <li class="odd"><a href="#">Fujitsu Siemens</a></li>
                    <li class="even"><a href="#">Motorola</a></li>
                    <li class="odd"><a href="#">Phillips</a></li>
                    <li class="even"><a href="#">Beko</a></li>
                </ul>
                <div class="banner_adds"> <a href="#"><img src="images/bann1.jpg" alt="" border="0" /></a> </div>
            </div>
            <!-- end of right content -->
        </div>
        <!-- end of main content -->
     <partial name="Footer"/>
    </div>
    <!-- end of main_container -->
</body>
</html>